/*
Copyright 2025 Balázs Zaicsek

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
/* Header for class io_github_zebalu_badidea_chdir_native_impl_jni_JniChDir */

#ifndef _Included_io_github_zebalu_badidea_chdir_native_impl_jni_JniChDir
#define _Included_io_github_zebalu_badidea_chdir_native_impl_jni_JniChDir
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_zebalu_badidea_chdir_native_impl_jni_JniChDir
 * Method:    chDir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_zebalu_badidea_chdir_native_1impl_jni_JniChDir_chDir
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
