/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_zebalu_badidea_chdir_native_impl_jni_JniChDir */

#ifndef _Included_io_github_zebalu_badidea_chdir_native_impl_jni_JniChDir
#define _Included_io_github_zebalu_badidea_chdir_native_impl_jni_JniChDir
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_zebalu_badidea_chdir_native_impl_jni_JniChDir
 * Method:    chDir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_zebalu_badidea_chdir_native_1impl_jni_JniChDir_chDir
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
